// Derived view regenerator. Inline (no subprocess) — the Python version
// shells out to scripts/rebuild_derived.py for legacy reasons; here it's
// a single function call.
//
// Determinism: `current.md`'s "as of" line uses the latest authored
// chart timestamp (not wall-clock now) so back-to-back rebuilds against
// unchanged canonical content produce byte-identical output.

import path from "node:path";
import {
  atomicWriteFile,
  ensureDir,
  iterNdjson,
  globPerDayFile,
  readTextIfExists,
} from "./fs-util.js";
import { latestEffectiveAt, parseIso } from "./time.js";
import { parseFrontmatter } from "./fs-util.js";

const HEADER =
  "<!-- generated by src/derived.ts — do not hand-edit. -->\n" +
  "<!-- this file is a disposable view; delete and regenerate freely. -->\n\n";

const VITALS_ORDER = [
  "temperature",
  "heart_rate",
  "bp_systolic",
  "bp_diastolic",
  "respiratory_rate",
  "spo2",
  "pain",
] as const;

export async function rebuildDerived(chartRoot: string): Promise<void> {
  const dir = path.join(chartRoot, "_derived");
  await ensureDir(dir);
  const views: Record<string, string> = {
    "current.md": await buildCurrent(chartRoot),
    "latest-vitals.md": await buildLatestVitals(chartRoot),
    "active-constraints.md": await buildActiveConstraints(chartRoot),
    "open-intents.md": await buildOpenIntents(chartRoot),
  };
  for (const [name, body] of Object.entries(views)) {
    await atomicWriteFile(path.join(dir, name), body);
  }
}

async function* iterEvents(chartRoot: string) {
  for (const p of await globPerDayFile(chartRoot, "events.ndjson")) {
    for await (const [, ev] of iterNdjson(p)) yield ev;
  }
}

async function* iterVitals(chartRoot: string) {
  for (const p of await globPerDayFile(chartRoot, "vitals.jsonl")) {
    for await (const [, v] of iterNdjson(p)) yield v;
  }
}

async function buildCurrent(chartRoot: string): Promise<string> {
  const activeIntents: any[] = [];
  const recentAssessments: any[] = [];
  for await (const ev of iterEvents(chartRoot)) {
    if (ev.type === "intent" && ev.status === "active") activeIntents.push(ev);
    if (ev.type === "assessment") recentAssessments.push(ev);
  }
  recentAssessments.sort((a, b) =>
    String(b.effective_at).localeCompare(String(a.effective_at)),
  );

  const asOfDate = await latestEffectiveAt(chartRoot);
  const asOfStr = asOfDate
    ? (await findOriginalIsoForLatest(chartRoot, asOfDate)) ??
      asOfDate.toISOString()
    : "(empty chart)";

  const lines: string[] = [HEADER, "# Current state\n"];
  lines.push(`_as of latest chart event: ${asOfStr}_\n`);
  lines.push(`## Active intents (${activeIntents.length})\n`);
  for (const ev of activeIntents) {
    const goal = ev.data?.goal ?? ev.subtype ?? "";
    lines.push(`- \`${ev.id}\` — ${goal}`);
  }
  lines.push("");
  lines.push("## Recent assessments (latest 5)\n");
  for (const ev of recentAssessments.slice(0, 5)) {
    const summary = ev.data?.summary ?? "";
    lines.push(`- \`${ev.id}\` (${ev.effective_at}) — ${summary}`);
  }
  lines.push("");
  return lines.join("\n");
}

/** Walk events + vitals, find the row whose parsed date == best, return its raw string. */
async function findOriginalIsoForLatest(
  chartRoot: string,
  best: Date,
): Promise<string | null> {
  for await (const ev of iterEvents(chartRoot)) {
    const t = parseIso(ev.effective_at);
    if (t && t.getTime() === best.getTime()) return String(ev.effective_at);
  }
  for await (const v of iterVitals(chartRoot)) {
    const t = parseIso(v.sampled_at);
    if (t && t.getTime() === best.getTime()) return String(v.sampled_at);
  }
  return null;
}

function vitalsSortKey(name: string): [number, string] {
  const idx = VITALS_ORDER.indexOf(name as (typeof VITALS_ORDER)[number]);
  return [idx === -1 ? VITALS_ORDER.length : idx, name];
}

async function buildLatestVitals(chartRoot: string): Promise<string> {
  const latest: Record<string, { t: Date; sample: any }> = {};
  for await (const v of iterVitals(chartRoot)) {
    const t = parseIso(v.sampled_at);
    if (!t) continue;
    const prior = latest[v.name];
    if (!prior || t > prior.t) latest[v.name] = { t, sample: v };
  }
  const lines: string[] = [HEADER, "# Latest vitals\n"];
  const keys = Object.keys(latest);
  if (keys.length === 0) {
    lines.push("_no vitals recorded_\n");
    return lines.join("\n");
  }
  keys.sort((a, b) => {
    const [aPos, aName] = vitalsSortKey(a);
    const [bPos, bName] = vitalsSortKey(b);
    if (aPos !== bPos) return aPos - bPos;
    return aName.localeCompare(bName);
  });
  for (const name of keys) {
    const v = latest[name].sample;
    const unit = v.unit ?? "";
    const src = v.source;
    const srcStr =
      src && typeof src === "object"
        ? src.ref ?? src.kind ?? "?"
        : String(src ?? "?");
    lines.push(
      `- **${name}** = ${v.value} ${unit} ` +
        `(at ${v.sampled_at}, source \`${srcStr}\`)`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

async function buildActiveConstraints(chartRoot: string): Promise<string> {
  const lines: string[] = [HEADER, "# Active constraints\n"];
  const text = await readTextIfExists(path.join(chartRoot, "constraints.md"));
  if (text === null) {
    lines.push("_no constraints file_\n");
    return lines.join("\n");
  }
  let body = text;
  if (body.startsWith("---")) {
    const end = body.indexOf("\n---", 3);
    if (end !== -1) body = body.slice(end + 4).replace(/^\n+/, "");
  }
  const bodyLines = body.split("\n");
  while (bodyLines.length && bodyLines[0].trimStart().startsWith("# ")) {
    bodyLines.shift();
  }
  while (bodyLines.length && bodyLines[0].trim() === "") {
    bodyLines.shift();
  }
  lines.push(bodyLines.join("\n"));
  return lines.join("\n");
}

async function buildOpenIntents(chartRoot: string): Promise<string> {
  const lines: string[] = [HEADER, "# Open intents\n"];
  let any = false;
  for await (const ev of iterEvents(chartRoot)) {
    if (ev.type !== "intent" || ev.status !== "active") continue;
    any = true;
    const d = ev.data ?? {};
    lines.push(`## \`${ev.id}\` — ${d.goal ?? ev.subtype ?? ""}\n`);
    if (d.rationale) lines.push(`**Rationale:** ${d.rationale}\n`);
    if (d.due_by) lines.push(`**Due by:** ${d.due_by}\n`);
    if (Array.isArray(d.success_criteria) && d.success_criteria.length) {
      lines.push("**Success criteria:**");
      for (const sc of d.success_criteria) lines.push(`- ${sc}`);
      lines.push("");
    }
    if (Array.isArray(d.contingencies) && d.contingencies.length) {
      lines.push("**Contingencies:**");
      for (const c of d.contingencies) {
        lines.push(`- if _${c?.trigger ?? ""}_: ${c?.action ?? ""}`);
      }
      lines.push("");
    }
  }
  if (!any) lines.push("_no active intents_\n");
  return lines.join("\n");
}
