#!/usr/bin/env python3
"""
pi-chart _derived/ regenerator.

Reads the canonical chart (patient.md, constraints.md, timeline/**) and emits
disposable views under _derived/. Nothing here is a source of truth.

Determinism: views must be a pure function of canonical content. The "as of"
line uses the latest chart event timestamp instead of wall-clock now so
rebuilds produce no diff unless canonical content changed.

Usage:
    python scripts/rebuild_derived.py [path/to/pi-chart]

Current views:
  - _derived/current.md           high-level state summary
  - _derived/latest-vitals.md     most recent value per vital metric
  - _derived/active-constraints.md  current allergies, code status, goals
  - _derived/open-intents.md      active care plans and orders
"""

from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path

try:
    import yaml
except ImportError:
    print(
        "Missing dependency 'pyyaml'. Install with:\n"
        "    pip install -r scripts/requirements.txt",
        file=sys.stderr,
    )
    sys.exit(2)


GENERATED_HEADER = (
    "<!-- generated by scripts/rebuild_derived.py — do not hand-edit. -->\n"
    "<!-- this file is a disposable view; delete and regenerate freely. -->\n\n"
)

# Clinical reading order; anything not in this list falls to the tail and is
# sorted alphabetically there.
VITALS_ORDER = (
    "temperature",
    "heart_rate",
    "bp_systolic",
    "bp_diastolic",
    "respiratory_rate",
    "spo2",
    "pain",
)


def iter_events(chart_root: Path):
    for events_path in sorted(chart_root.glob("timeline/*/events.ndjson")):
        with events_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                yield json.loads(line)


def iter_vitals(chart_root: Path):
    for vitals_path in sorted(chart_root.glob("timeline/*/vitals.jsonl")):
        with vitals_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                yield json.loads(line)


def _parse_iso(ts: str) -> datetime | None:
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00"))
    except (ValueError, TypeError, AttributeError):
        return None


def latest_chart_timestamp(chart_root: Path) -> str | None:
    """Max effective_at across events plus max sampled_at across vitals."""
    best: datetime | None = None
    best_str: str | None = None
    for ev in iter_events(chart_root):
        t = _parse_iso(ev.get("effective_at", ""))
        if t and (best is None or t > best):
            best, best_str = t, ev["effective_at"]
    for v in iter_vitals(chart_root):
        t = _parse_iso(v.get("sampled_at", ""))
        if t and (best is None or t > best):
            best, best_str = t, v["sampled_at"]
    return best_str


def build_current(chart_root: Path) -> str:
    active_intents = []
    recent_assessments = []
    for ev in iter_events(chart_root):
        if ev["type"] == "intent" and ev.get("status") == "active":
            active_intents.append(ev)
        if ev["type"] == "assessment":
            recent_assessments.append(ev)
    recent_assessments.sort(key=lambda e: e["effective_at"], reverse=True)

    as_of = latest_chart_timestamp(chart_root) or "(empty chart)"

    lines = [GENERATED_HEADER, "# Current state\n"]
    lines.append(f"_as of latest chart event: {as_of}_\n")
    lines.append(f"## Active intents ({len(active_intents)})\n")
    for ev in active_intents:
        goal = (ev.get("data") or {}).get("goal") or ev.get("subtype")
        lines.append(f"- `{ev['id']}` — {goal}")
    lines.append("")
    lines.append("## Recent assessments (latest 5)\n")
    for ev in recent_assessments[:5]:
        summary = (ev.get("data") or {}).get("summary", "")
        lines.append(f"- `{ev['id']}` ({ev['effective_at']}) — {summary}")
    lines.append("")
    return "\n".join(lines)


def _vitals_sort_key(name: str) -> tuple[int, str]:
    if name in VITALS_ORDER:
        return (VITALS_ORDER.index(name), name)
    return (len(VITALS_ORDER), name)


def build_latest_vitals(chart_root: Path) -> str:
    latest: dict[str, dict] = {}
    for v in iter_vitals(chart_root):
        name = v["name"]
        this_t = _parse_iso(v.get("sampled_at", ""))
        if this_t is None:
            continue
        if name not in latest:
            latest[name] = v
            continue
        prev_t = _parse_iso(latest[name].get("sampled_at", ""))
        if prev_t is None or this_t > prev_t:
            latest[name] = v

    lines = [GENERATED_HEADER, "# Latest vitals\n"]
    if not latest:
        lines.append("_no vitals recorded_\n")
        return "\n".join(lines)

    for name in sorted(latest, key=_vitals_sort_key):
        v = latest[name]
        unit = v.get("unit", "")
        src = v.get("source") or {}
        if isinstance(src, dict):
            src_str = src.get("ref") or src.get("kind") or "?"
        else:
            src_str = str(src)
        lines.append(
            f"- **{name}** = {v['value']} {unit} "
            f"(at {v['sampled_at']}, source `{src_str}`)"
        )
    lines.append("")
    return "\n".join(lines)


def build_active_constraints(chart_root: Path) -> str:
    path = chart_root / "constraints.md"
    lines = [GENERATED_HEADER, "# Active constraints\n"]
    if not path.exists():
        lines.append("_no constraints file_\n")
        return "\n".join(lines)
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            text = text[end + 4 :].lstrip("\n")
    # Drop the source body's top-level heading so it doesn't double the
    # derived view's own H1.
    body_lines = text.splitlines()
    if body_lines and body_lines[0].lstrip().startswith("# "):
        body_lines = body_lines[1:]
    # Trim leading blank line if present after heading removal.
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    lines.append("\n".join(body_lines))
    return "\n".join(lines)


def build_open_intents(chart_root: Path) -> str:
    lines = [GENERATED_HEADER, "# Open intents\n"]
    any_found = False
    for ev in iter_events(chart_root):
        if ev["type"] != "intent" or ev.get("status") != "active":
            continue
        any_found = True
        d = ev.get("data") or {}
        lines.append(f"## `{ev['id']}` — {d.get('goal', ev.get('subtype', ''))}\n")
        if "rationale" in d:
            lines.append(f"**Rationale:** {d['rationale']}\n")
        if "due_by" in d:
            lines.append(f"**Due by:** {d['due_by']}\n")
        if d.get("success_criteria"):
            lines.append("**Success criteria:**")
            for sc in d["success_criteria"]:
                lines.append(f"- {sc}")
            lines.append("")
        if d.get("contingencies"):
            lines.append("**Contingencies:**")
            for c in d["contingencies"]:
                lines.append(f"- if _{c.get('trigger', '')}_: {c.get('action', '')}")
            lines.append("")
    if not any_found:
        lines.append("_no active intents_\n")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    chart_root = Path(argv[1] if len(argv) > 1 else ".").resolve()
    derived = chart_root / "_derived"
    derived.mkdir(exist_ok=True)

    views = {
        "current.md": build_current(chart_root),
        "latest-vitals.md": build_latest_vitals(chart_root),
        "active-constraints.md": build_active_constraints(chart_root),
        "open-intents.md": build_open_intents(chart_root),
    }
    for name, text in views.items():
        (derived / name).write_text(text, encoding="utf-8")
        print(f"wrote {derived / name}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
