// Derived view regenerator. A thin formatter over the view primitives
// in `src/views/` (DESIGN §4.8). `_derived/` stays as a cached render
// for human grep; it is never authoritative.
//
// Determinism: `current.md`'s "as of" line uses the chart's latest
// authored timestamp (via currentState's default asOf resolution), not
// wall-clock now, so back-to-back rebuilds against unchanged canonical
// content produce byte-identical output.

import path from "node:path";
import {
  atomicWriteFile,
  ensureDir,
  readTextIfExists,
} from "./fs-util.js";
import {
  eventStartDate,
  eventStartIso,
  latestEffectiveAt,
  parseIso,
} from "./time.js";
import { iterNdjson, globPerDayFile } from "./fs-util.js";
import { patientRoot } from "./types.js";
import { currentState } from "./views/currentState.js";
import { openLoops } from "./views/openLoops.js";
import type {
  ContestedClaim,
  CurrentState,
  EventEnvelope,
  OpenLoop,
  PatientScope,
  TrendPoint,
} from "./types.js";

type CurrentStateAll = Extract<CurrentState, { axis: "all" }>;

const HEADER =
  "<!-- generated by src/derived.ts — do not hand-edit. -->\n" +
  "<!-- this file is a disposable view; delete and regenerate freely. -->\n\n";

const VITALS_ORDER = [
  "temperature",
  "heart_rate",
  "bp_systolic",
  "bp_diastolic",
  "respiratory_rate",
  "spo2",
  "pain",
] as const;

export async function rebuildDerived(scope: PatientScope): Promise<void> {
  const pr = patientRoot(scope);
  const dir = path.join(pr, "_derived");
  await ensureDir(dir);

  const latest = await latestEffectiveAt(pr);
  const asOfIso = latest
    ? (await findOriginalIsoForLatest(pr, latest)) ?? latest.toISOString()
    : null;

  const state = (await currentState({
    scope,
    axis: "all",
    ...(asOfIso ? { asOf: asOfIso } : {}),
  })) as CurrentStateAll;
  const loops = await openLoops({
    scope,
    ...(asOfIso ? { asOf: asOfIso } : {}),
  });

  const views: Record<string, string> = {
    "current.md": buildCurrent(state, asOfIso),
    "latest-vitals.md": buildLatestVitals(state.vitals),
    "active-constraints.md": await buildActiveConstraints(pr),
    "open-intents.md": buildOpenIntents(loops),
  };
  for (const [name, body] of Object.entries(views)) {
    await atomicWriteFile(path.join(dir, name), body);
  }
}

function buildCurrent(
  state: CurrentStateAll,
  asOfIso: string | null,
): string {
  const lines: string[] = [HEADER, "# Current state\n"];
  lines.push(`_as of latest chart event: ${asOfIso ?? "(empty chart)"}_\n`);
  const contestedById = contestedLookup(state.contested);

  lines.push(`## Active intents (${state.intents.length})\n`);
  for (const loop of state.intents) {
    const goal = (loop.intent.data as any)?.goal ?? loop.intent.subtype ?? "";
    lines.push(`- \`${loop.intent.id}\` — ${goal}${contestedSuffix(loop.intent.id, contestedById)}`);
  }
  lines.push("");

  const assessments = state.problems.slice(0, 5);
  lines.push("## Recent assessments (latest 5)\n");
  for (const ev of assessments) {
    const summary = (ev.data as any)?.summary ?? "";
    lines.push(
      `- \`${ev.id}\` (${eventStartIso(ev) ?? "unknown"}) — ${summary}${contestedSuffix(ev.id, contestedById)}`,
    );
  }
  lines.push("");

  lines.push(`## Active constraints (${state.constraints.length})\n`);
  for (const ev of state.constraints) {
    const summary = (ev.data as any)?.summary ?? ev.subtype ?? "constraint";
    lines.push(
      `- \`${ev.id}\` — ${summary}${contestedSuffix(ev.id, contestedById)}`,
    );
  }
  lines.push("");

  const observations = state.observations.slice(0, 5);
  lines.push("## Recent observations (latest 5)\n");
  for (const ev of observations) {
    const name = (ev.data as any)?.name ?? ev.subtype ?? "observation";
    const value = (ev.data as any)?.value;
    const summary = value !== undefined ? `${name} = ${value}` : `${name}`;
    lines.push(
      `- \`${ev.id}\` (${eventStartIso(ev) ?? "unknown"}) — ${summary}${contestedSuffix(ev.id, contestedById)}`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

function vitalsSortKey(name: string): [number, string] {
  const idx = VITALS_ORDER.indexOf(name as (typeof VITALS_ORDER)[number]);
  return [idx === -1 ? VITALS_ORDER.length : idx, name];
}

function buildLatestVitals(vitals: Record<string, TrendPoint>): string {
  const lines: string[] = [HEADER, "# Latest vitals\n"];
  const keys = Object.keys(vitals);
  if (keys.length === 0) {
    lines.push("_no vitals recorded_\n");
    return lines.join("\n");
  }
  keys.sort((a, b) => {
    const [aPos, aName] = vitalsSortKey(a);
    const [bPos, bName] = vitalsSortKey(b);
    if (aPos !== bPos) return aPos - bPos;
    return aName.localeCompare(bName);
  });
  for (const name of keys) {
    const v = vitals[name];
    const unit = v.unit ?? "";
    lines.push(
      `- **${name}** = ${v.value} ${unit} ` +
        `(at ${v.sampled_at}, source \`${v.source}\`)`,
    );
  }
  lines.push("");
  return lines.join("\n");
}

async function buildActiveConstraints(patientDir: string): Promise<string> {
  const lines: string[] = [HEADER, "# Active constraints\n"];
  const text = await readTextIfExists(path.join(patientDir, "constraints.md"));
  if (text === null) {
    lines.push("_no constraints file_\n");
    return lines.join("\n");
  }
  let body = text;
  if (body.startsWith("---")) {
    const end = body.indexOf("\n---", 3);
    if (end !== -1) body = body.slice(end + 4).replace(/^\n+/, "");
  }
  const bodyLines = body.split("\n");
  while (bodyLines.length && bodyLines[0].trimStart().startsWith("# ")) {
    bodyLines.shift();
  }
  while (bodyLines.length && bodyLines[0].trim() === "") {
    bodyLines.shift();
  }
  lines.push(bodyLines.join("\n"));
  return lines.join("\n");
}

function buildOpenIntents(loops: (OpenLoop | ContestedClaim)[]): string {
  const lines: string[] = [HEADER, "# Open intents\n"];
  const visibleLoops = loops.filter(
    (loop): loop is OpenLoop =>
      !("kind" in loop) || loop.kind !== "contested_claim",
  );
  if (!visibleLoops.length) {
    lines.push("_no active intents_\n");
    return lines.join("\n");
  }
  for (const loop of visibleLoops) {
    const ev = loop.intent;
    const d = (ev.data as Record<string, unknown> | undefined) ?? {};
    const goal = d.goal ?? ev.subtype ?? "";
    lines.push(`## \`${ev.id}\` — ${goal} [${loop.state}]\n`);
    if (d.rationale) lines.push(`**Rationale:** ${d.rationale}\n`);
    if (d.due_by) {
      const deltaLabel =
        loop.dueDeltaMinutes === undefined
          ? ""
          : ` (${formatMinutes(loop.dueDeltaMinutes)})`;
      lines.push(`**Due by:** ${d.due_by}${deltaLabel}\n`);
    }
    if (Array.isArray(d.success_criteria) && (d.success_criteria as unknown[]).length) {
      lines.push("**Success criteria:**");
      for (const sc of d.success_criteria as unknown[]) lines.push(`- ${sc}`);
      lines.push("");
    }
    if (Array.isArray(d.contingencies) && (d.contingencies as unknown[]).length) {
      lines.push("**Contingencies:**");
      for (const c of d.contingencies as any[]) {
        lines.push(`- if _${c?.trigger ?? ""}_: ${c?.action ?? ""}`);
      }
      lines.push("");
    }
  }
  return lines.join("\n");
}

function contestedLookup(
  contested: CurrentStateAll["contested"] | undefined,
): Map<string, string> {
  const out = new Map<string, string>();
  if (!contested) return out;
  for (const entries of Object.values(contested)) {
    for (const entry of entries) {
      out.set(entry.events[0], entry.events[1]);
      out.set(entry.events[1], entry.events[0]);
    }
  }
  return out;
}

function contestedSuffix(
  id: string,
  contestedById: Map<string, string>,
): string {
  const otherId = contestedById.get(id);
  return otherId ? ` (contested with \`${otherId}\`)` : "";
}

function formatMinutes(mins: number): string {
  if (mins === 0) return "now";
  const sign = mins < 0 ? "overdue by" : "in";
  const abs = Math.abs(mins);
  if (abs < 60) return `${sign} ${abs} min`;
  const h = Math.floor(abs / 60);
  const m = abs % 60;
  return m === 0 ? `${sign} ${h}h` : `${sign} ${h}h ${m}m`;
}

/** Find the raw ISO string in events/vitals that matches `best` exactly. */
async function findOriginalIsoForLatest(
  patientDir: string,
  best: Date,
): Promise<string | null> {
  for (const p of await globPerDayFile(patientDir, "events.ndjson")) {
    for await (const [, ev] of iterNdjson(p)) {
      const t = eventStartDate(ev as EventEnvelope);
      if (t && t.getTime() === best.getTime()) return eventStartIso(ev as EventEnvelope);
    }
  }
  for (const p of await globPerDayFile(patientDir, "vitals.jsonl")) {
    for await (const [, v] of iterNdjson(p)) {
      const t = parseIso(v?.sampled_at);
      if (t && t.getTime() === best.getTime()) return String(v.sampled_at);
    }
  }
  return null;
}
