import test from "node:test";
import assert from "node:assert/strict";
import path from "node:path";
import { promises as fs } from "node:fs";
import os from "node:os";
import { rebuildDerived } from "./derived.js";
import {
  makeEmptyPatient,
  appendRawEvent,
} from "./test-helpers/fixture.js";
import { patientRoot } from "./types.js";
import type { PatientScope } from "./types.js";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");

async function copyFixture(): Promise<PatientScope> {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), "pi-chart-derived-"));
  await fs.cp(REPO_ROOT, dir, {
    recursive: true,
    filter: (src) => !/node_modules|_derived\/.+\.md/.test(src),
  });
  return { chartRoot: dir, patientId: "patient_001" };
}

test("rebuild is deterministic against unchanged content", async () => {
  const scope = await copyFixture();
  await rebuildDerived(scope);
  const derivedPath = path.join(patientRoot(scope), "_derived/current.md");
  const before = await fs.readFile(derivedPath, "utf8");
  // Sleep one ms to ensure wall clock advances; deterministic version must
  // not include any wall-clock timestamp.
  await new Promise((r) => setTimeout(r, 5));
  await rebuildDerived(scope);
  const after = await fs.readFile(derivedPath, "utf8");
  assert.equal(before, after);
});

test("current.md 'as of' uses chart timestamp, not wall clock", async () => {
  const scope = await copyFixture();
  await rebuildDerived(scope);
  const text = await fs.readFile(
    path.join(patientRoot(scope), "_derived/current.md"),
    "utf8",
  );
  assert(text.includes("as of latest chart event: 2026-04-18T08:45"));
});

test("latest-vitals.md orders clinically (heart_rate before bp_systolic before spo2)", async () => {
  const scope = await copyFixture();
  await rebuildDerived(scope);
  const text = await fs.readFile(
    path.join(patientRoot(scope), "_derived/latest-vitals.md"),
    "utf8",
  );
  const hr = text.indexOf("heart_rate");
  const sys = text.indexOf("bp_systolic");
  const spo2 = text.indexOf("spo2");
  assert(hr > -1 && sys > -1 && spo2 > -1);
  assert(hr < sys, "heart_rate should appear before bp_systolic");
  assert(sys < spo2, "bp_systolic should appear before spo2");
});

test("rebuildDerived emits deterministic memory-proof.md with required headings", async () => {
  const scope = { chartRoot: REPO_ROOT, patientId: "patient_002" };
  const tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), "pi-chart-memory-proof-"));
  await fs.cp(REPO_ROOT, tmpRoot, {
    recursive: true,
    filter: (src) => !/node_modules|_derived\/.+\.md/.test(src),
  });
  const tmpScope = { ...scope, chartRoot: tmpRoot };
  await rebuildDerived(tmpScope);
  const proofPath = path.join(patientRoot(tmpScope), "_derived/memory-proof.md");
  const before = await fs.readFile(proofPath, "utf8");
  await rebuildDerived(tmpScope);
  const after = await fs.readFile(proofPath, "utf8");
  assert.equal(before, after);
  assert(before.includes("generated by src/derived.ts"));
  for (const heading of [
    "## What happened",
    "## Why it mattered",
    "## Evidence/provenance",
    "## Uncertainty",
    "## Open loops",
    "## Next-shift handoff",
  ]) {
    assert(before.includes(heading), heading);
  }
});

test("active-constraints.md does not double the # Constraints heading", async () => {
  const scope = await copyFixture();
  await rebuildDerived(scope);
  const text = await fs.readFile(
    path.join(patientRoot(scope), "_derived/active-constraints.md"),
    "utf8",
  );
  // Top H1 is "Active constraints" — body should not contain another `# Constraints`.
  const h1Count = text.split("\n").filter((l) => l.startsWith("# ")).length;
  assert.equal(h1Count, 1);
});

function intent(
  id: string,
  at: string,
  extras: Record<string, unknown> = {},
) {
  return {
    id,
    type: "intent",
    subtype: "care_plan",
    subject: "patient_001",
    encounter_id: "enc_001",
    effective_at: at,
    recorded_at: at,
    author: { id: "x", role: "rn_agent" },
    source: { kind: "agent_inference" },
    certainty: "planned",
    status: "active",
    data: { goal: "watch" },
    links: { supports: [] },
    ...extras,
  };
}

test("current.md contested annotations clear after resolver and open-intents excludes contested_claim duplicates", async () => {
  const scope = await makeEmptyPatient();
  await appendRawEvent(scope, "2026-04-18", intent("evt_intent_old", "2026-04-18T08:00:00-05:00"));
  await appendRawEvent(scope, "2026-04-18", intent("evt_intent_new", "2026-04-18T08:10:00-05:00", {
    links: {
      supports: [],
      contradicts: [{ ref: "evt_intent_old", basis: "new evidence" }],
    },
  }));
  await appendRawEvent(scope, "2026-04-18", {
    id: "evt_anchor",
    type: "observation",
    subtype: "vital_sign",
    subject: "patient_001",
    encounter_id: "enc_001",
    effective_at: "2026-04-18T09:15:00-05:00",
    recorded_at: "2026-04-18T09:15:00-05:00",
    author: { id: "x", role: "rn" },
    source: { kind: "monitor_extension" },
    certainty: "observed",
    status: "final",
    data: { name: "spo2", value: 95 },
    links: { supports: [] },
  });
  await rebuildDerived(scope);
  const current = await fs.readFile(
    path.join(patientRoot(scope), "_derived/current.md"),
    "utf8",
  );
  const openIntents = await fs.readFile(
    path.join(patientRoot(scope), "_derived/open-intents.md"),
    "utf8",
  );
  assert(current.includes("`evt_intent_old` — watch (contested with `evt_intent_new`)"));
  assert(current.includes("`evt_intent_new` — watch (contested with `evt_intent_old`)"));
  assert.equal(openIntents.match(/evt_intent_new/g)?.length ?? 0, 1);

  await appendRawEvent(scope, "2026-04-18", intent("evt_intent_fix", "2026-04-18T09:20:00-05:00", {
    links: {
      supports: [],
      supersedes: ["evt_intent_old"],
      resolves: ["evt_intent_new"],
    },
  }));
  await rebuildDerived(scope);
  const currentAfter = await fs.readFile(
    path.join(patientRoot(scope), "_derived/current.md"),
    "utf8",
  );
  assert(!currentAfter.includes("contested with"), currentAfter);
});
